language: ruby
rvm:
  - 2.3.1
  - jruby
  - rbx
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile
git:
  submodules: false
env:
  global:
  - COVERAGE=1
  - TRAVIS=1
matrix:
  allow_failures:
  - rvm: rbx
  exclude:
  - rvm: jruby
    gemfile: spec/gemfiles/rails_5_0.gemfile
sudo: false
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

script:
- bundle exec rspec --format d
- bundle exec codeclimate-test-reporter
