language: ruby
script: "bundle exec rspec --exclude-pattern 'spec/gemfiles/vendor/**/*'"
rvm:
  - 2.2.1
  - jruby
  - rbx
gemfile:
  - spec/gemfiles/Gemfile-rails-3-2
  # rails 4:
  - spec/gemfiles/Gemfile-rails-4-0
  - spec/gemfiles/Gemfile-rails-4-1
  - spec/gemfiles/Gemfile-rails-4-2
env:
  global:
  - TRAVIS=1
  # codeclimate.com repo token:
  - secure: Kh43fq+MfpGNfQ/0IBhMnbzixVS5+K2QFPPwYfcS9ISgMASY2MAbNS1ZaD9HJ5Ynta8tnqS2QodwfQavDYI4tsFXcJ8RXbGK7GX2BKKuhH2ZfwuTGgltg0W1zTJR/18PL6jlMqon4lPnjaQQhis/WhBHqjkxHNIDzYWocZo/hc0=
matrix:
  allow_failures:
  - rvm: rbx
  exclude:
  - rvm: 2.2.1
    gemfile: spec/gemfiles/Gemfile-rails-3-2
cache: bundler
